path: 'C:\zshahpouri\programming1\Final\Lifelines public health dataset\2022\csv\continuous\Participants_Aggregated_Zipcode_Continuous.txt'
path_general: 'C:\zshahpouri\programming1\Final\Lifelines public health dataset\2022\csv\continuous\Participants_Aggregated_Zipcode_General_Continuous.txt'
